// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDYvvQDIsCoy3xGWfSwRLnaLIkiYUPGiKQ',
    appId: '1:768647160081:web:c503c2b7cad51570792cb0',
    messagingSenderId: '768647160081',
    projectId: 'aula-crud-fb',
    authDomain: 'aula-crud-fb.firebaseapp.com',
    databaseURL: 'https://aula-crud-fb-default-rtdb.firebaseio.com',
    storageBucket: 'aula-crud-fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbzs9H5G99YtPwg2p14XalIp7OCiZ6w78',
    appId: '1:768647160081:android:5d830c47e0945aef792cb0',
    messagingSenderId: '768647160081',
    projectId: 'aula-crud-fb',
    databaseURL: 'https://aula-crud-fb-default-rtdb.firebaseio.com',
    storageBucket: 'aula-crud-fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAL5W7Xate4bfe1RS2dCGQNRIBvUWZAWk0',
    appId: '1:768647160081:ios:ae595ce9fc451ed4792cb0',
    messagingSenderId: '768647160081',
    projectId: 'aula-crud-fb',
    databaseURL: 'https://aula-crud-fb-default-rtdb.firebaseio.com',
    storageBucket: 'aula-crud-fb.appspot.com',
    iosClientId: '768647160081-t5e5b1ufv3ro2j55t0230i17a2ld1kc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFirebase2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAL5W7Xate4bfe1RS2dCGQNRIBvUWZAWk0',
    appId: '1:768647160081:ios:ae595ce9fc451ed4792cb0',
    messagingSenderId: '768647160081',
    projectId: 'aula-crud-fb',
    databaseURL: 'https://aula-crud-fb-default-rtdb.firebaseio.com',
    storageBucket: 'aula-crud-fb.appspot.com',
    iosClientId: '768647160081-t5e5b1ufv3ro2j55t0230i17a2ld1kc5.apps.googleusercontent.com',
    iosBundleId: 'com.example.appFirebase2',
  );
}
